version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # NGINX serves HTML on port 80 inside the container
    depends_on:
      - backend
