version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
    networks:
      - noteapp-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Port host:container
    depends_on:
      - backend
    restart: always
    networks:
      - noteapp-network

networks:
  noteapp-network:
